# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160215_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish'),
        ),
    ]
