# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160326_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='blog/%Y/%m/%d', verbose_name='post image'),
        ),
    ]
